### ISSUE TITLE
Error: 'copy_n' is not a member of 'std' (gcc 8.3.0)

### ISSUE THREAD

**Issue by ghost** [tenacityteam/tenacity-legacy#662]
### Guidelines

- [X] I have read the guidelines.

### Version/Commit hash

4df39adc

### Describe the bug.

Follow the directions listed in [BUILDING.md](https://git.sr.ht/~tenacity/tenacity/tree/master/BUILDING.md), with gcc 8.3.0. See the error due to a missing "copy_n" function in the standard c++ libraries.

### Expected behavior

I expected Tenacity to build without error so I could install it (since there do not appear to be any packaged releases).

### OS

MX Linux 19.4 / Devuan Beowulf 3.1

### Additional context

I installed MX Linux 19.4, then changed source repos to Devuan Beowulf 3.1, so gcc is from Devuan repos.
Since GitHub refuses to process the log, I uploaded it to [Lufi](https://upload.disroot.org/r/GTbY4MSf#XVcCrg6lbRm0sa6GUo4IYwswnPwQnNph5rsLtamtCyk=). 
Pass: impedingseminarnintendobackspinrecycleruninjured

### This issue is not a duplicate

- [X] I have confirmed this issue isn't a duplicate.

**Comment by akleja** [comment]
Thanks for the bug rapport and the log!
I encountered the same issue a while back, but forgot to fix it.
Just posted a PR which should resolve the issue: https://github.com/tenacityteam/tenacity/pull/663
Would be glad if you could try it out to confirm if it resolves it.

**Comment by ghost** [comment]
@akleja That particular bug is no longer present, but I still cannot build tenacity.
```
FAILED: src/CMakeFiles/Tenacity.dir/effects/SBSMSEffect.cpp.o
/usr/bin/ccache /usr/bin/c++  -DCMAKE -DEXPERIMENTAL_DRAGGABLE_PLAY_HEAD -DEXPERIMENTAL_EASY_CHANGE_KEY_BINDINGS -DEXPERIMENTAL_EFFECT_MANAGEMENT -DEXPERIMENTAL_FULL_WASAPI -DEXPERIMENTAL_HALF_WAVE -DEXPERIMENTAL_KEY_VIEW -DEXPERIMENTAL_MODULE_PREFS -DEXPERIMENTAL_NOISE_REDUCTION -DEXPERIMENTAL_NOTETRACK_OVERLAY -DEXPERIMENTAL_NYQUIST_SPLIT_CONTROL -DEXPERIMENTAL_PUNCH_AND_ROLL -DEXPERIMENTAL_REALTIME_AUDACITY_EFFECTS -DEXPERIMENTAL_SCIENCE_FILTERS -DEXPERIMENTAL_SCROLLING_LIMITS -DEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL -DEXPERIMENTAL_SCRUBBING_SUPPORT -DEXPERIMENTAL_SPECTRAL_EDITING -DEXPERIMENTAL_SYNC_LOCK -DEXPERIMENTAL_THEMING -DEXPERIMENTAL_TWO_TONE_TIME_RULER -DEXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS -DEXPERIMENTAL_ZOOM_TOGGLE_BUTTON -DHAVE_IPO -DHAVE_LRINT -DHAVE_LRINTF -DHAVE_MLOCK -DSTRINGS_API="" -DSTRING_UTILS_API="" -DTENACITY_DLL_API="" -DTenacity_EXPORTS -DUTILITY_API="" -DWXUSINGDLL -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING=1 -D_SILENCE_CXX17_NEGATORS_DEPRECATION_WARNING=1 -D__WXGTK3__ -D__WXGTK__ -Isrc/private -I../include -I../src -I../lib-src/libnyquist/. -I../libraries/lib-string-utils -I../libraries/lib-strings -I../libraries/lib-utility -isystem /usr/local/lib/wx/include/gtk3-unicode-3.1 -isystem /usr/local/include/wx-3.1 -isystem /usr/include/lilv-0 -isystem /usr/include/suil-0 -isystem /usr/local/lib/portsmf/include -isystem /usr/include/gtk-3.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/fribidi -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/uuid -isystem /usr/include/harfbuzz -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/x86_64-linux-gnu/dbus-1.0/include -pthread -g   -include /home/ziproot/Downloads/tenacity/build/src/private/configunix.h -DAUDACITY_VERSION=3 -DAUDACITY_RELEASE=0 -DAUDACITY_REVISION=2 -DAUDACITY_MODLEVEL=0 -DAUDACITY_VERSION_STRING=L\"Audacity-3.0.2-891-gdb3f6ae\" -DAUDACITY_FILE_VERSION=L\"3,0,2,0\" -DPROHIBITED==delete -Dsafenew=new -DWXINTL_NO_GETTEXT_MACRO -D_DEBUG=1 -DIS_ALPHA -DUSE_ALPHA_MANUAL -pthread -std=gnu++17 -MD -MT src/CMakeFiles/Tenacity.dir/effects/SBSMSEffect.cpp.o -MF src/CMakeFiles/Tenacity.dir/effects/SBSMSEffect.cpp.o.d -o src/CMakeFiles/Tenacity.dir/effects/SBSMSEffect.cpp.o -c ../src/effects/SBSMSEffect.cpp
../src/effects/SBSMSEffect.cpp: In static member function ‘static double EffectSBSMS::getInvertedStretchedTime(double, double, _sbsms_::SlideType, double)’:
../src/effects/SBSMSEffect.cpp:203:17: error: ‘class _sbsms_::Slide’ has no member named ‘getInverseStretchedTime’; did you mean ‘getStretchedTime’?
    return slide.getInverseStretchedTime(outputTime);
                 ^~~~~~~~~~~~~~~~~~~~~~~
                 getStretchedTime
[562/749] Building CXX object src/CMakeFiles/Tenacity.dir/effects/TruncSilence.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by akleja** [comment]
@PeacefulPotato  Could you open a separate issue for this problem since it's not related to the earlier?
In the meantime, have you tried building without sbsms? `-DSBSMS=OFF`
